server:
  port: 82
spring:
  application:
    name: demo-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: demo-common
          uri: lb://demo-common
          predicates:
            - Path=/common/{segment},
          filters:
            - SetPath=/user/{segment}